# Generated by Django 3.0.9 on 2020-08-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_pricing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='stripe_price_id',
            field=models.CharField(default='django-free-trial', max_length=50),
            preserve_default=False,
        ),
    ]
